#!/bin/sh
# Check for symbols already defined in the system Compose file

# syms is from https://github.com/rrthomas/syms

UNICODE_REGEX="[^<](U[0-9a-fA-F]{4,5})[^>]"
# FIXME: {hyphen-macron,fractions}.xcompose contain lots of valid duplicates
OUR_FILES="arrows.xcompose \
        bullets.xcompose \
        cjk.xcompose \
        dashes-hyphens.xcompose \
        dingbats.xcompose \
        enclosed.xcompose \
        fractions.xcompose \
        historical.xcompose \
        hyphen-macron.xcompose \
        invisible.xcompose \
        math.xcompose \
        typographic.xcompose \
        fraktur.xcompose \
        dotXcompose.xcompose"

find_unicode () {
    cat "$@" | rep 's/#.*$//' - | syms -s $UNICODE_REGEX | sort | uniq
}

find_unicode /usr/share/X11/locale/en_US.UTF-8/Compose > compose.syms
find_unicode $OUR_FILES > ours.syms
grep -F -x -f ours.syms compose.syms > overlap.syms
